name: Test & Deploy

on:
  workflow_dispatch:

  push:
    branches:
      - main
jobs:
    deploy:
      name: Deploy to render.com
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to production
          uses: johnbeynon/render-deploy-action@0.0.8
          with:
            api-key: ${{ secrets.RENDER_TOKEN }}
            service-id: ${{ secrets.RENDER_SERVICE_ID }}

    watch:
      name: Deploy to render.com
      runs-on: ubuntu-latest
      steps:
        - name: Wait for Render Deployment
          uses: bounceapp/render-action@0.7.1
          with:
            render-token: ${{ secrets.RENDER_TOKEN }}
            github-token: ${{ secrets.GITHUB_TOKEN }}
            service-id: ${{ secrets.RENDER_SERVICE_ID }}
            retries: 20
            wait: 16000
            sleep: 30000