name: Test & Deploy

on:
  workflow_dispatch:

  push:
    branches:
      - main
jobs:
    deploy:
      name: Deploy to render.com
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to production
          uses: johnbeynon/render-deploy-action@v0.0.8
          with:
            api-key: ${{ secrets.RENDER_TOKEN }}
            service-id: ${{ secrets.RENDER_SERVICE_ID }}

    watch:
      name: Monitor Render Deployment
      runs-on: ubuntu-latest
      steps:
        - name: Wait for Render Deployment
          uses: bounceapp/render-action@0.7.1
          with:
            render-token: ${{ secrets.RENDER_TOKEN }}
            github-token: ${{ secrets.GITHUB_TOKEN }}
            service-id: ${{ secrets.RENDER_SERVICE_ID }}
            retries: 20
            wait: 16000
            sleep: 30000

    end-to-end:
      name: End to End Tests
      runs-on: ubuntu-latest
      needs: [deploy, watch]
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install dependencies
          run: npm install
        - name: Run e2e tests
          run: npm run staging:test:e2e